<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelpagesite</name>
   <tag></tag>
   <elementGuidId>38f19f60-c705-473a-9c27-c1dc287e9ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table[@name='tblInhouseMultiple'][1]//tbody//td/p)[12]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
